export const SEARCH_ARTICLES = "SEARCH_ARTICLE";
export const SCROLL_SEARCH = "SCROLL_SEARCH";
export const GET_SAVED_ATRICLES = "GET_SAVED_ATRICLES";
export const DEL_SAVED_ARTICLE = "DEL_SAVED_ARTICLE";
